from glob import glob

def gen_source_list_sub(path: str, name: str, recursive=False):
  if recursive: wildcard = path + "/**/*.cpp"
  else: wildcard = path + "/*.cpp"

  sources = glob(wildcard, recursive=recursive)
  
  for i in range(len(sources)):
    sources[i] = "${CMAKE_CURRENT_SOURCE_DIR}/" + sources[i]

  var_prefix = f"STM32PP_{name}"

  src_list = "\n  ".join(sources)

  sourcelist = f"set({var_prefix}_SOURCES \n  " + f"{src_list} \n) \n"
                 
  return sourcelist

dirs = ["audio", "canopen", "core", "device", "ethernet", "gfx", "modbus", "objnet", "radio", "serial", "usb"]

print("# Autogenerated by gen_sources.py\n")

print(gen_source_list_sub("src/", "COMMON", False))

for dir in dirs:
  print(gen_source_list_sub("src/" + dir, dir.swapcase(), True))